image: node:16

stages:
  - build
  - test
  - deploy

build-app:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - npm install
    - npm test
      
deploy_to_lab:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - 'echo -e "Host texel02\n\tHostName shell2.doc.ic.ac.uk\n\tUser zw4021\n\tRequestTTY yes\n\tIdentityFile ~/.ssh/id_rsa\n\tRemoteCommand ssh texel02" > ~/.ssh/config'
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - rm -f zw4021@texel02:/vol/project/2023/60021/g236002112/web/*
    - scp -r build/* zw4021@texel02:/vol/project/2023/60021/g236002112/web
  only:
    - master
